runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /eventos
  static_files: www/eventos.html
  upload: www/eventos.html